default_context:
  project_name: Example
  project_description: Very interesting example, yeah!
  author_full_name: Nikita Sivakov
  author_email: sivakov512@gmail.com
  github_org: sivakov512
  github_repo: python-microservice-template-example
  proto_repository: git@github.com:sivakov512/python-microservice-template-proto.git
